# Generated by Django 5.1.7 on 2025-04-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='breathingexercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meditation_images/'),
        ),
        migrations.AddField(
            model_name='meditation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meditation_images/'),
        ),
        migrations.AlterField(
            model_name='meditation',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
