# Generated by Django 5.1.7 on 2025-04-09 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_breathingexercise_image_meditation_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restsession',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
