# Generated by Django 5.1.7 on 2025-04-11 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_restsession_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breathingexercise',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='meditation',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='breathingexercise',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breathingexercise',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meditation',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meditation',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
