# Generated by Django 5.1.7 on 2025-04-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_breathingexercise_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breathingexercise',
            name='duration',
            field=models.PositiveIntegerField(default=5, help_text='Длительность в минутах'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meditation',
            name='duration',
            field=models.PositiveIntegerField(default=3, help_text='Длительность в минутах'),
            preserve_default=False,
        ),
    ]
