# Generated by Django 5.1.7 on 2025-04-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_alter_breathingexercise_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breathingexercise',
            name='duration',
            field=models.PositiveIntegerField(default=5, help_text='Длительность в минутах'),
        ),
        migrations.AlterField(
            model_name='meditation',
            name='duration',
            field=models.PositiveIntegerField(default=5, help_text='Длительность в минутах'),
        ),
    ]
